# Titanic Survival Prediction
-----------------------------------
### Objective
Build a machine learning model to predict whether a passenger survived the Titanic disaster.

-------------------------------------------------------------------------------------------------------------
### Importing libraries

In [113]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

-------------------------------------------------------------------------------------------------------------
### Loading dataset

In [114]:
titan = pd.read_csv(r'C:\Users\chand\Downloads\Titanic-Dataset.csv')
titan.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

----------------------------------
### Data Preprocessing
- Missing value analysis
- Feature Engineering
- Encoding

In [115]:
# Missing values analysis
titan.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Filling the missing values
titan['Age'] = titan.Age.fillna(value = titan.Age.median())
titan['Embarked'] = titan.Embarked.fillna(value = titan.Embarked.mode()[0])
titan = titan.drop('Cabin',axis=1)
titan.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [117]:
# Feature Engineering
titan["Family_size"] = titan["SibSp"] + titan["Parch"]
titan.groupby("Family_size")["Survived"].sum()

Family_size
0     163
1      89
2      59
3      21
4       3
5       3
6       4
7       0
10      0
Name: Survived, dtype: int64

In [ ]:
# Encoding
titan["Sex"] = titan["Sex"].map({"male":0,"female":1})
titan

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_size
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,28.0,1,2,W./C. 6607,23.4500,S,3
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C,0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,Q,0

-----------------------------------------------
### Feature Selection and train-test split
Features:
- Pclass
- Age
- Fare
- Sex
- Family_Size

Target:
- Survived

In [129]:
X = titan[["Pclass","Age","Fare","Sex","Family_size"]]
y = titan["Survived"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

---------------------------------------------------------------------------
### Model training and evaluation

In [132]:
dm = DecisionTreeClassifier(random_state=5)
dm.fit(X_train,y_train)
pre = dm.predict(X_test)
acc = accuracy_score(pre,y_test)
print("Decision Tree Accuracy:",acc)

Decision Tree Accuracy: 0.7597765363128491

-------------------------------------
### Feature Importance

In [133]:
dm.feature_importances_

array([0.11284995, 0.27507281, 0.19715999, 0.333913  , 0.08100426])

----------------------------
## Conclusion (Version 1)
The Decision Tree model achieved an accuracy of 80.45%. Among the selected features, Sex and Pclass were the most influential predictors of survival. The project demonstrates a complete machine learning workflow including preprocessing, feature engineering, model training, and evaluation.

------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------
### Model Comparision